---
pipeline:
  package:
    image: maven:3-jdk-8
    volumes:
    - name: package
      path: /root/.m2/
    commands:
    - mvn -Prelease-all -DskipTests clean install -U
    # pull: true
    #environment:
    #  - KEY=VALUE
    #secrets: [key1, key2]
