---
kind: "pipeline"
name: "default"
workspace:
steps:
  - name: "build"
    image: maven:3-jdk-8
    commands:
      - "mvn clean package"
    depends_on: [ "clone" ]
  - name: "publish"
    image: plugins/docker
    repo: rocketmq
    registry: hz.4yutech.com:7070
    settings:
      username: "user1"
      password: "Test@123456"
      dockerfile: "Dockerfile"
      tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "build" ]
    
trigger:
  branch:
  - release
