---
kind: "pipeline"
name: "default"
workspace:
steps:
  - name: "build"
    image: maven:3-jdk-8
    commands:
      - "mvn -Prelease-all -DskipTest clean install -U"
    depends_on: [ "clone" ]
  - name: "publish"
    image: plugins/docker
    repo: http://hz.4yutech.com:7070/rocketmq
    registry: http://hz.4yutech.com:7070/rocketmq
    commands:
    - "echo ${username},${password},${DRONE_BUILD_NUMBER}"
    settings:
      username: 
        from_secret: "username"
      password: 
        from_secret: "password"
      dockerfile: "Dockerfile"
      tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "build" ]
    
trigger:
  branch:
  - release
