---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3-jdk-8
  commands:
  - mvn clean compile
- name: package
  image: maven:3-jdk-8
  commands:
  - mvn -Prelease-all -DskipTests clean install -U
