workspace:
  base: /srv/drone-demo
  path: .

pipeline:
  package:
    image: maven:3-jdk-8
    commands:
    - mvn -Prelease-all -DskipTests clean install -U
    # pull: true
    #environment:
    #  - KEY=VALUE
    #secrets: [key1, key2]
