---
kind: "pipeline"
name: "default"
workspace:
steps:
  - name: "build"
    image: maven:3-jdk-8
    commands:
      - "mvn clean package"
    depends_on: [ "clone" ]
  - name: "publish"
    image: plugins/docker
    repo: chinaloryu/rocketmq
    settings:
      username: "chinaloryu"
      password: "2019#Test"
      dockerfile: "Dockerfile"
      tags: "${DRONE_BUILD_NUMBER}"
    depends_on: [ "build" ]
    
trigger:
  branch:
  - release
