notifications:
  email:
    recipients:
      - dev@rocketmq.incubator.apache.org
  on_success: change
  on_failure: always
  
matrix:
  include:
  # On OSX, run with default JDK only.
  - language: java
  - os: osx
  # On Linux, run with specific JDKs only.
  - language: java
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"
  - language: java
  - os: linux
    env: CUSTOM_JDK="oraclejdk7"
  - language: java
  - os: linux
    env: CUSTOM_JDK="openjdk7"

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi
#
#os:
#  - linux
#  - osx
#jdk:
#  - oraclejdk8
#  - oraclejdk7
#  - openjdk7


script:
  - travis_retry mvn --batch-mode clean apache-rat:check
  - travis_wait 60 mvn --batch-mode clean package findbugs:check

after_success:
  - mvn clean cobertura:cobertura coveralls:report
